export interface IReporte {}

export interface GetPdfDto {
  base64: string;
}

// Generated by https://quicktype.io

export interface IReporteGeneralDto {
  IdArticulo: number;
  IdPais: number;
  NombreComercial: string;
  IdTitularRegistro: number;
  NroRegistro: string;
  IdTipoProducto: number;
  IdFormulador: number;
  IdGrupoQuimico: null;
  IdTipoFormulacion: number;
  Concentracion: string;
  FlgActivo: boolean;
  IdFormuladorNavigation: IDFormuladorNavigation;
  IdGrupoQuimicoNavigation: null;
  IdPaisNavigation: IDPaisNavigation;
  IdTipoFormulacionNavigation: IDTipoFormulacionNavigation;
  IdTipoProductoNavigation: IDTipoProductoNavigation;
  IdTitularRegistroNavigation: IDTitularRegistroNavigation;
  Composicions: Composicion[];
  Documentos: Documento[];
  Usos: Uso[];
  Caracteristicas: Caracteristica[];
  ProductoFabricantes:         ProductoFabricante[];
  ProductoFormuladors:         ProductoFormulador[];
}


export interface ProductoFormulador {
  IdProducto:             number;
  IdFormuladorNavigation: IDFormuladorNavigation;
}

export interface IDFormuladorNavigation {
  IdFormulador:  number;
  NomFormulador: string;
  estado:        boolean;
}


export interface ProductoFabricante {
  IdArticulo:             number;
  IdFabricanteNavigation: IDFabricanteNavigation;
}

export interface IDFabricanteNavigation {
  IdFabricante:     number;
  NombreFabricante: string;
  Estado:           boolean;
}

export interface Caracteristica {
  IdArticulo: number;
  IdItem: number;
  IdAplicacion: null;
  IdClase: number;
  IdToxicologica: number;
  IdAplicacionNavigation: null;
  IdClaseNavigation: IDClaseNavigation;
  IdToxicologicaNavigation: IDToxicologicaNavigation;
}

export interface IDClaseNavigation {
  IdClase: number;
  Descripcion: string;
  estado: boolean;
  IdTipoProducto: number;
  IdTipoProductoNavigation: IDTipoProductoNavigation;
}

export interface IDTipoProductoNavigation {
  IdTipoProducto1: number;
  NomTipoProducto: string;
  estado: boolean;
}

export interface IDToxicologicaNavigation {
  IdToxicologica: number;
  Descripcion: string;
  estado: boolean;
}

export interface Composicion {
  IdArticulo: number;
  Iditem: number;
  IngredienteActivo: number;
  FormuladorMolecular: string;
  idGrupoQuimico: number;
  ContracionIA: string;
  GrupoQuimicoNavegation: GrupoQuimicoNavegation;
  IngredienteActivoNavigation: IngredienteActivoNavigation;
}

export interface GrupoQuimicoNavegation {
  IdGrupoQuimico: number;
  NomGrupoQuimico: string;
  estado: boolean;
}

export interface IngredienteActivoNavigation {
  IngredenteActivo: number;
  NomIngredienteActivo: string;
  estado: boolean;
}

export interface Documento {
  IdArticulo: number;
  IdItem: number;
  IdTipoDocumento: number;
  Fecha: string;
  NomDocumento: string;
  IdTipoDocumentoNavigation: IDTipoDocumentoNavigation;
}

export interface IDTipoDocumentoNavigation {
  IdTipoDocumento: number;
  Nombre: string;
  estado: boolean;
}

export interface IDFormuladorNavigation {
  IdFormulador: number;
  NomFormulador: string;
  estado: boolean;
}

export interface IDPaisNavigation {
  IdPais: number;
  NomPais: string;
  estado: boolean;
}

export interface IDTipoFormulacionNavigation {
  IdTipoFormulacion: number;
  CodTipoFormulacion: string;
  NomTipoFormulacion: string;
  estado: boolean;
}

export interface IDTitularRegistroNavigation {
  IdTitularRegistro: number;
  NomTitularRegistro: string;
  estado: boolean;
}

export interface Uso {
  IdArticulo: number;
  IdItem: number;
  IdCultivo: number;
  NombreCientificoCultivo: null;
  IdNomCientificoPlaga: number;
  Dosis: null;
  IdCultivoNavigation: IDCultivoNavigation;
  IdNomCientificoPlagaNavigation: IDNomCientificoPlagaNavigation;
}

export interface IDCultivoNavigation {
  IdCultivo: number;
  NombreCultivo: string;
  estado: boolean;
}

export interface IDNomCientificoPlagaNavigation {
  IdNomCientificoPlaga: number;
  NombreCientificoPlaga: string;
  estado: boolean;
}
