export interface IUsersDto {
  IdUsuario: number;
  ApellidoPaterno: string;
  ApellidoMaterno: string;
  Nombres: string;
  Credencial: string;
  Email: string;
  UsuarioPais?: any[];
}

// Generated by https://quicktype.io

export interface AddOrEditUserDto {
  idUsuario: number;
  apellidoPaterno: string;
  apellidoMaterno: string;
  nombres: string;
  credencial: string;
  textoClave: string;
  fechaRegistro: string;
  usuarioRegistro: string;
  fechaModificacion: string;
  usuarioModificacion: string;
  email: string;
}
